### ISSUE TITLE
Datapack broken on 1.20.4

### ISSUE THREAD

**Issue by RMEngelbrecht** [RubenRME/Campfire-Leather#1]
Copying this report by Turncoat from PMC  for completeness:

> tested in 1.20.4 vanilla MC
> it seems not working in 1.20.4
> 
> I can put in rotten flesh to campfire and soul campfire. but flesh never turn to leather, just burn and disappear after some cooking time.
> 
> ---
> test case 01: default setting : 40 rotten flesh to campfire, 40 rotten flesh to soul campfire, 0 leather result.(I expected only soul campfire accept rotten flesh, but normal campfire still accept.)
> 
> test case 02: after /function `#rme:campfire_leather/toggle_campfire` command : 40 rotten flesh to campfire, 40 rotten flesh to soul campfire, 0 leather result.
> 
> test case 03: after `/function #rme:campfire_leather/reset` command : 40 rotten flesh to campfire, 40 rotten flesh to soul campfire, 0 leather result.
>
> ---
> I cooked total 240 rotten flesh, 120 rotten flesh were cooked by soul campfire, and getting 0 leather. so I decide this bug report.****

**Comment by RMEngelbrecht** [comment]
Broken on 1.20.2 as well it seems

**Comment by RubenRME** [comment]
Fixed in v1.1.3

**Comment by RMEngelbrecht** [comment]
Fixed in v1.1.2
