### ISSUE TITLE
Still broken

### ISSUE THREAD

**Issue by Rikumo1978** [RubenRME/Campfire-Leather#2]
Hello,

I've just installed this mod today and I get the same issue as the Closed issue you have on here, I've tried converting at least 90 rotten flesh and I have yet to get a single Leather from it. I have enabled it on the Soul campfire, but just for fun I've tried it on both campfire types after enabling the other one as well. Still nothing.

**Comment by RMEngelbrecht** [comment]
@Rikumo1978 Hi, sorry for the late reply. Just to make sure: this is the mod jar from Modrinth on a singleplayer world?
I'll look into this asap

**Comment by Rikumo1978** [comment]
Hello,

Actually, after I created a new server and re-modded everything it’s now
working reliably! Thanks so much! I just tested it out :-)

Donate!
<https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=QTMUA3K4LXYQS>

Thanks,
Charles

**Comment by RMEngelbrecht** [comment]
Awesome! Glad it got resolved. I did notice myself the mod version sometimes doesn't work well on a server. Not sure why.
In the future the datapack version is reliable on server!
