### ISSUE TITLE
1.19.x port please?

### ISSUE THREAD

**Issue by Naithedan** [RubenRME/Campfire-Leather#3]
As stated, specifically 1.19.2 if possible. This mod should be used way more and have more attention given the uselessness of rotten flesh.

**Comment by RMEngelbrecht** [comment]
Thank you for the suggestion! I'm quite busy right now but will do so asap!

**Comment by RMEngelbrecht** [comment]
Hey @Naithedan! Sorry of the delay but I just released 1.1.5 for 1.19.x!

Would be great if you could test it out ^^
Closing this issue for now.
