### ISSUE TITLE
(DP) Works, but hoppers don't collect?

### ISSUE THREAD

**Issue by roracle** [RubenRME/Campfire-Leather#4]
From what I've experienced, the datapack works fine. However, when I place a campfire on a hopper and cook the rotten flesh, the hopper doesn't collect the item like it does other vanilla items. Instead, the leather is removed completely.

RME's Campfire Leather version 1.1.5
Minecraft 1.21.1

Thank you!

**Comment by RMEngelbrecht** [comment]
Thanks for your report! Definitely a use case I oversaw when writing it. Need to investigate whether this is fixable on the current way leather is spawned on the campfire or whether it requires a full rewrite of that bit, but I'm expecting the latter I'm afraid.

**Comment by RMEngelbrecht** [comment]
After a lot of testing I've concluded the current pickup rates of the converted leather are about the same as those of vanilla items, neither of which are 100%. Be aware that this might feel like it's even lower with the converted leather due to the ~20% conversion chance.
